### ISSUE TITLE
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html.

### ISSUE THREAD

**Issue by shun99** [novoda/bintray-release#123]
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/yghysdr/Desktop/MyOkHttp-master/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0

my Android studio
gradle 2.14.1
bintray-release version 0.4.0   or 0.3.4

**Comment by StefMa** [comment]
Can you post your build.gradle?
You have to apply the plugin after the android-library plugin...

On May 16, 2017 4:49 AM, "shun99" <notifications@github.com> wrote:

To honour the JVM settings for this build a new JVM will be forked. Please
consider using the daemon: https://docs.gradle.org/2.14.
1/userguide/gradle_daemon.html.

FAILURE: Build failed with an exception.

   -

   Where:
   Build file '/Users/yghysdr/Desktop/MyOkHttp-master/app/build.gradle'
   line: 1
   -

   What went wrong:
   A problem occurred evaluating project ':app'.

java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin
: Unsupported major.minor version 52.0

my Android studio
gradle 2.14.1
bintray-release version 0.4.0 or 0.3.4

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/novoda/bintray-release/issues/123>, or mute the thread

**Comment by blundell** [comment]
> Unsupported major.minor version 52.0

I believe you may be using the wrong version of Java? 6 when it needs 7/8 or viceversa
