### ISSUE TITLE
Convert to Kotlin 

### ISSUE THREAD

**Issue by StefMa** [novoda/bintray-release#145]
Hey guys

what do think your it?
Converting the whole plugin to Kotlin?

**Comment by blundell** [comment]
closing as not an issue

(whilst it may happen, I don't want an open issue lingering round whilst conversations happen elsewhere)

it's not a no and its not a yes :)

**Comment by StefMa** [comment]
@blundell normally I use the github issues also for "feature requests" or "backlog". Isn't that something like that? I would prefer to not closing it...

**Comment by blundell** [comment]
We have a Jira backlog. 

If this is a backlog story it would need more fleshing out and less bias that you seem to already have decided to move to kolin :)

**Comment by StefMa** [comment]
How can I access that jira?
Or maybe other developers who wants to contribute to bintray-release?
:thinking:

2017-11-10 9:21 GMT+01:00 Paul Blundell <notifications@github.com>:

**Comment by Mecharyry** [comment]
I've created a follow-up issue on this topic because I believe there should be a discussion between all of the maintainers of this project please see https://github.com/novoda/bintray-release/issues/148

In regards to the JIRA backlog, I'm planning on moving over issues to GH project instead so that it is public for everyone.
