### ISSUE TITLE
Provide better API for multi module projects

### ISSUE THREAD

**Issue by StefMa** [novoda/bintray-release#172]
In a multi module project each module has to add the plugin and configure by themself.
Something like:
```
AwesomeLib
-- module1
-- module2
```

Each module should contain the following code:
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "com.novoda:bintray-release:0.8.0"
    }
}

publish {
    userOrg = 'novoda'
    groupId = 'com.novoda.multimodule'
    artifactId = 'module1' // or module2
    uploadName = 'MultiModule'
    publishVersion = "0.1"
    website = 'https://github.com/novoda/MultiModule'
}
```

That leads to duplicated code and unnecessary maintenance.
Most of the time only the `artifactId` will change. Other properties are the same.

We should provide a better API where I can configure the `plugin` block in a top-level `build.gradle` file. Each module can override everything but shouldn't do that...

See also:
https://github.com/novoda/bintray-release/issues/16#issuecomment-360821068

**Comment by tasomaniac** [comment]
I'm not sure about the complexity it brings. 

If the concern is possible mistakes resulting from this duplication, users can extract project level constant to be used in the configuration. 

Otherwise this duplication is not bad. 

Also another option is that configuration can be extracted into a separate `gradle` script which configures each module depending on some params. 

This is definitely possible with current version and :-1: for anything that complicates the plugin.

**Comment by StefMa** [comment]
Hmm, thanks for that feedback.

Today I've tried it here https://github.com/grandcentrix/ThirtyInch/pull/140 and IMO this looks very okaisch 😄 

I'm with you.
I think that will lead to unnecessary overhead/complexity on our plugin side ...
