### ISSUE TITLE
merged aar 

### ISSUE THREAD

**Issue by omarDG** [novoda/bintray-release#200]
Hi,
I use the library to upload (first) aar to my Bintray account. The process is successfully done and I'm able to compile my hosted library.
My second test was to upload a library which contains anoter aar file. The resulted POM file to Bintray has a dependency tag with that third party aar definition. But When i try to compile the new hosted library. I get 
Failed to resolve.
One more thing, I'm not able to see the 3rd party aar in my file structure in Bintray.
Any ideas?

**Comment by StefMa** [comment]
Libraries don't include other libraries by default. They only "reference"
them via the pom file.

Which means the following:
Your project (which includes the second libraries) should add two
repositories. One which contains where to find your first libraries (the
aar) and a second which contains your second libraries.

Example:
The aar is only available in mavenLocal. The second libraries (which
depends on the fist aar) is only available via jcenter.
With that config you have to include both repository. MavenLocal and
jcenter...

On Mar 2, 2018 5:13 PM, "omarDG" <notifications@github.com> wrote:

Hi,
I use the library to upload (first) aar to my Bintray account. The process
is successfully done and I'm able to compile my hosted library.
My second test was to upload a library which contains anoter aar file. The
resulted POM file to Bintray has a dependency tag with that third party aar
definition. But When i try to compile the new hosted library. I get
Failed to resolve.
One more thing, I'm not able to see the 3rd party aar in my file structure
in Bintray.
Any ideas?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/novoda/bintray-release/issues/200>, or mute the thread

**Comment by mr-archano** [comment]
The reply from @StefMa is correct, closing this issue as it's related to consumer setup.
