### ISSUE TITLE
Javadoc error on non-Android projects

### ISSUE THREAD

**Issue by hendraanggrian** [novoda/bintray-release#251]
On a [non-Android project](https://github.com/hendraanggrian/ktfx), I'm getting error `javadoc: error - No public or protected classes found to document.` with new version 0.9. This issue isn't reproducible on version 0.8.1.

**Comment by mr-archano** [comment]
Hey @hendraanggrian thanks for the heads-up. Version 0.9 is still using the normal mechanism provided by the Java plugin in order to generate and collect the javadocs as artifact to upload to bintray. Maybe the issue is related to the fact your library is all Kotlin hence the javadoc task is not able to find any input - although I would expect that to do nothing and not fail the build.

Cold you provide detailed repro-steps on how to reproduce the issue?

**Comment by hendraanggrian** [comment]
Sorry for not being too specific. The only sub-module failing the whole `javadoc` build needed for `bintrayUpload` is `ktfx-coroutines`. Turns out, simple `javadoc.isEnabled = false` fixes it.
