### ISSUE TITLE
why my aar file is not include .so file  that uploaded to jcenter 

### ISSUE THREAD

**Issue by NodeGIS** [novoda/bintray-release#256]
I upload package successful, but the aar and jar file are not include my .so JNI file both. why?

this is package code:
`gradlew clean build bintrayUpload -PbintrayUser=myuser
-PbintrayKey=mykey  -PdryRun=false
`

```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 28



    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        abortOnError false
    }
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }


}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'com.android.support:appcompat-v7:28.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}


apply plugin: 'com.novoda.bintray-release'

def siteUrl = 'http://xxxxx.github.io'
publish{

    repoName = 'mymaven'
    userOrg = 'xxx'
    groupId = 'com.xxxx'
    artifactId = 'xxxxx-opengl'
    publishVersion = '2.6.7'
    desc = 'something'
    website = siteUrl
}
tasks.withType(Javadoc) {
    options.addStringOption('Xdoclint:none', '-quiet')
    options.addStringOption('encoding', 'UTF-8')
    options.addStringOption('charSet', 'UTF-8')
}


```

**Comment by StefMa** [comment]
That is excped and how gradle/maven works.
No single dependency will be included in the final aar/jar file. All will
only be referenced in a so called POM file.

You have to create a "fatAar" when you want to include files in your aar.
But that is not recommended.

On Dec 4, 2018 11:46 AM, "NodeGIS" <notifications@github.com> wrote:

I upload package successful, but the aar and jar file are not include my
.so JNI file both. why?

this is package code:
gradlew clean build bintrayUpload -PbintrayUser=myuser -PbintrayKey=mykey
-PdryRun=false

apply plugin: 'com.android.library'

android {
    compileSdkVersion 28



    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner
"android.support.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles
getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        abortOnError false
    }
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }


}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'com.android.support:appcompat-v7:28.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation
'com.android.support.test.espresso:espresso-core:3.0.2'
}


apply plugin: 'com.novoda.bintray-release'

def siteUrl = 'http://xxxxx.github.io'
publish{

    repoName = 'mymaven'
    userOrg = 'xxx'
    groupId = 'com.xxxx'
    artifactId = 'xxxxx-opengl'
    publishVersion = '2.6.7'
    desc = 'something'
    website = siteUrl
}
tasks.withType(Javadoc) {
    options.addStringOption('Xdoclint:none', '-quiet')
    options.addStringOption('encoding', 'UTF-8')
    options.addStringOption('charSet', 'UTF-8')
}



—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/novoda/bintray-release/issues/256>, or mute the thread
