### ISSUE TITLE
How to add aar to the library?

### ISSUE THREAD

**Issue by wellbranding** [novoda/bintray-release#265]
Our library uses another library internally. That library is accessed with maven path and also gradle dependency. Then I publish our library, client cannot easily integrate library, without specifying **the maven path of another dependency**. How can we make sure, that **only we** would include that library, without forcing **client to add** that maven directory?

**Comment by StefMa** [comment]
I don't get the question.
Your library has a dependency which is only available in your internal
repository?
When a client now what's to include your library they have to add your
internal repository... And this is what you not want, right?

**Comment by mr-archano** [comment]
Hi @wellbranding, in order to achieve what you describe - assuming I understand it correctly and the library you depend on is already published too - you need to ensure the pom file of your library includes the library you depend on as part of the `implementation` configuration, like [this](https://github.com/novoda/no-player/blob/develop/core/build.gradle#L62-L64):
```
implementation 'com.google.android.exoplayer:exoplayer:2.9.6'
implementation 'com.android.support:support-annotations:28.0.0'
```

The `bintray-release` plugin will then generate the pom file for you including those dependencies: 
https://bintray.com/novoda/snapshots/download_file?file_path=com%2Fnovoda%2Fno-player%2FSNAPSHOT-45%2Fno-player-SNAPSHOT-45.pom

```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.novoda</groupId>
  <artifactId>no-player</artifactId>
  <version>SNAPSHOT-45</version>
  <packaging>aar</packaging>
  <dependencies>
    <dependency>
      <groupId>com.google.android.exoplayer</groupId>
      <artifactId>exoplayer</artifactId>
      <version>2.9.6</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>support-annotations</artifactId>
      <version>28.0.0</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>
```
This will be enough for your clients to understand that they need to pull the additional dependencies when getting your library. Note that all those artifacts need to be published on some maven repository, better if on the same repo you use to publish yours.
