### ISSUE TITLE
Don't fail if artifact already exists [error 409]

### ISSUE THREAD

**Issue by TomasValenta** [novoda/bintray-release#274]
Hello,

first thank you for this great Gradle plugin! We faced only one small issue with an artifacts upload. I've already created issue in the [gradle-bintray-plugin](https://github.com/bintray/gradle-bintray-plugin/issues/283) repository, I just wanted to make sure that this issue has been correctly addressed and is not related (or can be resolved) to this "extension" ;)

Thank you,
Tom

**Comment by mr-archano** [comment]
thanks @TomasValenta but this plugin is using the [`bintray/gradle-bintray-plugin`](https://github.com/bintray/gradle-bintray-plugin/issues/283) to perform the upload to Bintray, so I'm afraid there's nothing we can do (as not in control of the failing task, nor in control of their behaviour).
I will close this issue because not applicable, but thanks for your interest and your feedback 👍
