### ISSUE TITLE
Doesn't work with any newer version of the Gradle Plugin and/or Gradle

### ISSUE THREAD

**Issue by afollestad** [novoda/bintray-release#63]
This library hasn't worked for months now, I get a warning that's worded something like "cannot access first() from list".

**Comment by blundell** [comment]
Can you give us an example project for which it does not work? Works fine on all our proj's

**Comment by afollestad** [comment]
https://github.com/afollestad/bridge and https://github.com/afollestad/material-dialogs are both examples. 

<img width="594" alt="screen shot 2015-07-17 at 1 07 04 pm" src="https://cloud.githubusercontent.com/assets/1820165/8753888/d0126930-2c84-11e5-8ccc-c877977e2783.png">

**Comment by afollestad** [comment]
The problem goes away if you remove bintray-release, which I did; I'm guessing it's an incompatibility issue with the next version (currently in beta) of Gradle and/or the Gradle plugins.

**Comment by afollestad** [comment]
Looks like this is the same as https://github.com/novoda/bintray-release/issues/56, although I'm using Gradle 2.5.  @blundell

**Comment by ouchadam** [comment]
**cc* @Dorvaryn I believe this is the same issue we saw in https://github.com/novoda/rxpresso when it was an inner module

**Comment by afollestad** [comment]
Build Tools 23.0.0, SDK v23 (Marshmallow), Gradle Plugin 1.3.0, and Google libs (AppCompat, etc.) 23.0.0 are all all now.

This library still does not work.

**Comment by hzsweers** [comment]
The problem is pretty simple. As they're preparing for Jack and Jill, the compilation tasks are getting moved around. The problem is here:

https://github.com/novoda/bintray-release/blob/master/core%2Fsrc%2Fmain%2Fgroovy%2Fcom%2Fnovoda%2Fgradle%2Frelease%2FAndroidLibrary.groovy#L17-L18

The compile configuration doesn't exist yet at that point now. Maybe you should postpone it until after evaluation.

This is a great example of why you should have tests.

**Comment by hzsweers** [comment]
Opened a pull request in https://github.com/novoda/bintray-release/pull/66. Please take a look when possible.
